### ISSUE TITLE
Legacy S3 URLs

### ISSUE THREAD

**Issue by Skizu** [hkusu/s3-upload-action#10]
When creating urls for the file [here](https://github.com/hkusu/s3-upload-action/blob/16ca91cc27270d765b3b4ddb996eb961835b3cd4/src/main.js#L114), you are using the legacy `s3-Region` format, instead of the current `s3.Region` format as noted in the [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html).

**Comment by hkusu** [comment]
Thank you! I will fix it in the next version.

**Comment by hkusu** [comment]
I fixed it with #19.
