### ISSUE TITLE
file-path not accepting directory

### ISSUE THREAD

**Issue by satish-dosapati** [hkusu/s3-upload-action#12]
Hi Team,

I am trying to upload my test results to S3, here I am storing my results to <Path>/reposts directory.
Under the report directory I have different test suites like
reports/testsuite1/report.html
reports/testsuite2/report.html

if I use file-path: reports/testsuite1/report.html , able to upload that file to S3
But if I try to upload reports directory like file-path: reports I am getting "**EISDIR: illegal operation on a directory, read**" error
I gave chmod 777 permissions to that directory, still no use.

Can you please guide me on how to upload directory to S3

**Comment by hkusu** [comment]
Sorry,

As the README.md says:

> Currently, only single file upload is supported.

Only single files can be uploaded.
